# -*- coding: utf-8 -*-
"""pysparkcode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UdVtrljnUqrLr8Rj_mpOQ78X3XOxhyIN
"""

pip install pyspark

from pyspark.sql import SparkSession
from pyspark.ml.evaluation import RegressionEvaluator
from pyspark.ml.recommendation import ALS

# Setup Spark Session
spark = SparkSession.builder.appName('Recommender').getOrCreate()

data = spark.read.csv('product_ratings.csv', inferSchema=True, header=True)

product_info = spark.read.csv('product_info.csv', inferSchema=True, header=True)

als = ALS(maxIter=5,
          regParam=0.01,
          userCol="customer_id",
          itemCol="product_id",
          ratingCol="Rate")

model = als.fit(data)

user1 = data.filter(data['customer_id'] == 38984).select(['product_id', 'customer_id'])

recommendations = model.transform(user1)

user_recommendations = recommendations.join(product_info, on='product_id', how='left')

user_recommendations.orderBy('prediction', ascending=False).select('Product Name', 'Category','prediction').distinct().show()